included:
    - Sources

# rule identifiers to exclude from running
disabled_rules:
    - cyclomatic_complexity

shorthand_operator: warning

# some rules are only opt-in
opt_in_rules:
    - empty_count
